### ISSUE TITLE
[BUG] Unresponsive buttons

### ISSUE THREAD

**Issue by TQCnoARosto** [DeDiamondPro/ChatShot#5]
When using [ChatPatches](https://github.com/mrbuilder1961/ChatPatches) all the copy button on the right side of the chat get misaligned, so when trying to copy a line you are actually copying the line above.

This is because ChatPatches has a setting to shif the chat upwards, can you make the copy mod responsive?

![image](https://github.com/user-attachments/assets/1c603120-89c3-4524-a820-6c495c9fb714)

**Comment by DeDiamondPro** [comment]
Hi,
this is because ChatPatches doesn't update the `toChatLineY` function so it would return the correct line for a corresponding y value, without this it is impossible to get the correct line for where your mouse is. And even if this would be updated, because of the way it shifts the chat, I would have absolutely no way to find where the chat moved, making it impossible to adapt to the new positioning.

**Comment by mrbuilder1961** [comment]
the issue should be fixed in the latest dev build, referenced in [ChatPatches#187](https://github.com/mrbuilder1961/ChatPatches/issues/187#issuecomment-2241968562). however, i'm not sure what you mean about not being able to access the shifted chat position. assuming the mixin is working, it should propagate and allow you to access the updated value there. however, if you'd rather me put the `shiftChat` option in the fabric ObjectShare or something, just let me know and i can do that as well

**Comment by DeDiamondPro** [comment]
> the issue should be fixed in the latest dev build, referenced in [ChatPatches#187](https://github.com/mrbuilder1961/ChatPatches/issues/187#issuecomment-2241968562). however, i'm not sure what you mean about not being able to access the shifted chat position. assuming the mixin is working, it should propagate and allow you to access the updated value there. however, if you'd rather me put the `shiftChat` option in the fabric ObjectShare or something, just let me know and i can do that as well

The main reason is that I mixin to ChatScreen, then at the draw method use `toChatLineY` to get the lineY and then I convert this back to pixel value Y using `(int) ((height - 40) / chatScale - ((int) chatLineY + 1) * lineHeight)` (same calculation MC uses) since there is no function for this. I am going to see if its possible for me to mixin to ChatHud instead and hook into where it renders a line there which would fix this issue but I'm not 100% sure I can get the complete message from there

**Comment by DeDiamondPro** [comment]
I have a (mostly) working version but there are still some weird graphical issues I have to fix, hopefully it'll be ready tomorrow

**Comment by DeDiamondPro** [comment]
Fixed in 1.0.3 https://modrinth.com/mod/chatshot/version/cEnckQTT You also need the new build of ChatPatches
