### ISSUE TITLE
Incompatibility with Symbol Chat

### ISSUE THREAD

**Issue by FaNToMaSikkk** [DeDiamondPro/ChatShot#6]
### Describe the bug
The mod is not compatible with the Symbol Chat mod; with this mod, messages do not copy. Without Symbol Chat, everything works fine.

### Basic Informations

- OS Windows 11
- Symbol Chat 1.2.2
- Fabric Version 0.15.11
- Version Minecraft 1.20.4
- Active Mods:
    - Fabric API 0.97.1
    - ChatShot 1.0.1
    - Cloth Config API 13.0.121
    - Symbol Chat 1.2.2
    - Mod Menu 9.2.0

**Comment by DeDiamondPro** [comment]
Because of the way symbolchat takes control over mouse presses, chatshot can not detect a mouse press. I have updated my code to take priority which will make chatshot work, however if you have the symbol menu open and press on the screenshot button behind it, it will take a screenshot. I have no good way to detect or fix this. The compatibility improvement will be included in the next release.

**Comment by DeDiamondPro** [comment]
Mostly fixed in 1.0.3
